on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: 'Godot version'
        required: false
        default: ''
      release_artifact:
        description: 'Release artifact'
        required: false
        default: 'true'

jobs:
  godot:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Build artifact
        run: bundle exec rake godot:build_artifact VERSION=${{ github.event.inputs.godot_version }}

      - name: Artifact
        run: |
          echo "path=$(find . -name 'godot_*.deb')" >> $GITHUB_OUTPUT
          echo "version=$(pkg/opt/godot/bin/godot --version | cut -d '.' -f 1-3)" >> $GITHUB_OUTPUT
        id: artifact

      - if: github.event.inputs.release_artifact == 'true'
        name: Create release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: ${{ steps.artifact.outputs.version }}
          tag_name: ${{ steps.artifact.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ steps.artifact.outputs.path }}
